### ISSUE TITLE
Buildpack build of `example-ruby-sinatra` dies because controller wants a Docker image.

### ISSUE THREAD

**Issue by technosophos** [deis/workflow#106]
When I try to deploy `example-ruby-sinatra`, the build fails with a 500 from Controller.

In the logs, the problem seems to be that controller is trying to find an image for a buildpack release even though the builder does not build images for buildpacks (it just builds slugs and runs the slugrunner):

```
⇒  k --namespace=deis logs deis-workflow-o2uml
waiting for etcd at 10.247.174.157:4100...
addgroup: gid '0' in use
Syncing...
Creating tables ...
Creating table django_admin_log
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_groups
Creating table auth_user_user_permissions
Creating table auth_user
Creating table django_content_type
Creating table django_session
Creating table django_site
Creating table django_auth_ldap_testuser
Creating table django_auth_ldap_testprofile
Creating table south_migrationhistory
Creating table corsheaders_corsmodel
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for authtoken:
 - Migrating forwards to 0001_initial.
 > authtoken:0001_initial
 - Loading initial data for authtoken.
Installed 0 object(s) from 0 fixture(s)
Running migrations for api:
 - Migrating forwards to 0025_auto__chg_field_app_id.
 > guardian:0001_initial
 > guardian:0002_auto__add_field_groupobjectpermission_object_pk__add_field_userobjectp
 > guardian:0003_update_objectpermission_object_pk
 > guardian:0004_auto__del_field_groupobjectpermission_object_id__del_unique_groupobjec
 > guardian:0005_auto__chg_field_groupobjectpermission_object_pk__chg_field_userobjectp
 > api:0001_initial
 > api:0002_drop_djcelery
 > api:0003_drop_socialaccount
 > api:0004_add_custom_perms
 > api:0005_auto__add_push__add_unique_push_app_uuid
 > api:0006_auto__add_field_release_summary
 > api:0007_auto__del_flavor__del_unique_flavor_owner_id__del_layer__del_unique_la
 > api:0008_auto__add_field_release_image
 > api:0009_auto__chg_field_container_state
 > api:0010_auto__add_field_build_sha__add_field_build_procfile__add_field_build_d
 > api:0011_auto__add_domain
 > api:0012_auto__add_limit__add_unique_limit_app_uuid__add_field_config_limit
 > api:0013_auto__del_limit__del_unique_limit_app_uuid__del_field_config_limit__ad
 > api:0014_auto__add_field_config_tags
 > api:0015_migration_config_defaults
 > api:0016_drop_allauth
 > api:0017_auto__del_cluster__del_field_app_cluster
 > api:0018_drop_field_release_image__chg_field_release_build
 > api:0019_fix_dockerfile_empty_value
 > api:0020_auto__del_field_container_state
 > api:0021_auto__add_certificate
 > api:0022_auto__add_field_key_fingerprint
 > api:0023_key_fingerprints
 > api:0024_auto__chg_field_key_fingerprint__del_unique_key_owner_id__add_unique_k
 > api:0025_auto__chg_field_app_id
 - Loading initial data for api.
Installed 0 object(s) from 0 fixture(s)
Running migrations for guardian:
- Nothing to migrate.
 - Loading initial data for guardian.
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.humanize
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > django_auth_ldap
 > json_field
 > rest_framework
 > south
 > corsheaders
 > registry
 > web

Migrated:
 - rest_framework.authtoken
 - api
 - guardian
[2015-12-16 22:31:10 +0000] [128] [INFO] Starting gunicorn 19.3.0
[2015-12-16 22:31:10 +0000] [128] [INFO] Listening at: http://0.0.0.0:8000 (128)
[2015-12-16 22:31:10 +0000] [128] [INFO] Using worker: sync
[2015-12-16 22:31:10 +0000] [132] [INFO] Booting worker with pid: 132
[2015-12-16 22:31:10 +0000] [133] [INFO] Booting worker with pid: 133
[2015-12-16 22:31:10 +0000] [134] [INFO] Booting worker with pid: 134
Publishing DB state to etcd...
[2015-12-16 22:31:10 +0000] [135] [INFO] Booting worker with pid: 135
Done Publishing DB state to etcd.
deis-controller running...
[2015-12-16 22:31:10 +0000] [140] [INFO] Booting worker with pid: 140
[2015-12-16 22:31:10 +0000] [141] [INFO] Booting worker with pid: 141
[2015-12-16 22:31:10 +0000] [142] [INFO] Booting worker with pid: 142
[2015-12-16 22:31:11 +0000] [143] [INFO] Booting worker with pid: 143
[2015-12-16 22:31:11 +0000] [144] [INFO] Booting worker with pid: 144
WARNING Not Found: /
10.246.29.1 "GET / HTTP/1.1" 404 74 "curl/7.43.0"
10.246.29.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.0.0-dev"
10.246.29.1 "POST /v2/auth/register/ HTTP/1.1" 400 42 "Deis Client v2.0.0-dev"
10.246.29.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.0.0-dev"
10.246.29.1 "POST /v2/auth/register/ HTTP/1.1" 201 251 "Deis Client v2.0.0-dev"
10.246.29.1 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.0.0-dev"
10.246.29.1 "POST /v2/keys/ HTTP/1.1" 201 653 "Deis Client v2.0.0-dev"
INFO hearty-checkers: config hearty-checkers-a45a22b updated
INFO hearty-checkers: release hearty-checkers-v1 created
INFO [hearty-checkers]: matt created initial release
10.246.29.1 "POST /v2/apps/ HTTP/1.1" 201 204 "Deis Client v2.0.0-dev"
10.246.29.1 "POST /v2/hooks/push HTTP/1.1" 201 442 "curl/7.39.0"
10.246.29.1 "POST /v2/hooks/config HTTP/1.1" 200 199 "deis-builder"
INFO hearty-checkers: build hearty-checkers-eaa6fc1 created
INFO hearty-checkers: release hearty-checkers-v2 created
INFO [hearty-checkers]: matt deployed e159088
INFO Pulling Docker image 10.247.243.26:5000/hearty-checkers:git-e1590887
ERROR Internal Server Error: /v2/hooks/build
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 403, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/app/api/views.py", line 129, in create
    return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 410, in post_save
    build.create(self.user)
  File "/app/api/models.py", line 736, in create
    source_version=source_version)
  File "/app/api/models.py", line 849, in new
    release.publish()
  File "/app/api/models.py", line 865, in publish
    publish_release(source_image, self.config.values, self.image, deis_registry)
  File "/app/registry/dockerclient.py", line 118, in publish_release
    return client.publish_release(source, config, target, deis_registry)
  File "/app/registry/dockerclient.py", line 42, in publish_release
    self.pull(repo, src_tag)
  File "/app/registry/dockerclient.py", line 74, in pull
    log_output(stream)
  File "/app/registry/dockerclient.py", line 106, in log_output
    raise docker.errors.DockerException(chunk)
DockerException: {"errorDetail":{"message":"Error: image hearty-checkers:git-e1590887 not found"},"error":"Error: image hearty-checkers:git-e1590887 not found"}

10.246.29.1 "POST /v2/hooks/build HTTP/1.1" 500 27 "deis-builder"
```

The full record of what I did to produce this is here: https://gist.github.com/technosophos/773167a92d11ca1edbf9

**Comment by arschles** [comment]
@smothiki I think this is fixed by https://github.com/deis/workflow/pull/95, no?

**Comment by smothiki** [comment]
I mean technically fixed if we turn off authentication on minio

**Comment by arschles** [comment]
ok, can you fix the authentication problem by copying the minio credentials secret into the apps's namespace?

**Comment by technosophos** [comment]
I have confirmed that the build no longer dies because of the docker image thing. I'm closing this, as other bugs cover the remaining problems.
