### ISSUE TITLE
Pulling a non-existent docker image results in a 500 instead of a good error message

### ISSUE THREAD

**Issue by helgi** [deis/workflow#159]
```
deis pull deis/go-example -a knotty-henhouse
Creating build... Error:
500 INTERNAL SERVER ERROR
<h1>Server Error (500)</h1>
```

```
INFO [knotty-henhouse]: helgi deployed deis/go-example
INFO Pulling Docker image deis/go-example:latest
ERROR Internal Server Error: /v2/apps/knotty-henhouse/builds/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 140, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/app/api/views.py", line 117, in create
    return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 254, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models.py", line 726, in create
    source_version=source_version)
  File "/app/api/models.py", line 839, in new
    release.publish()
  File "/app/api/models.py", line 855, in publish
    publish_release(source_image, self.config.values, self.image, deis_registry)
  File "/app/registry/dockerclient.py", line 118, in publish_release
    return client.publish_release(source, config, target, deis_registry)
  File "/app/registry/dockerclient.py", line 42, in publish_release
    self.pull(repo, src_tag)
  File "/app/registry/dockerclient.py", line 74, in pull
    log_output(stream)
  File "/app/registry/dockerclient.py", line 106, in log_output
    raise docker.errors.DockerException(chunk)
DockerException: {"errorDetail":{"message":"Error: image deis/go-example:latest not found"},"error":"Error: image deis/go-example:latest not found"}
```

**Comment by helgi** [comment]
I was running custom image without realising but latest master has this problem

```
deis pull deis/go-example -a knotty-henhouse
Creating build... Error: Post http://10.3.0.247/v2/apps/knotty-henhouse/builds/: dial tcp 10.3.0.247:80: getsockopt: connection timed out
```

Not seeing any real error messages right now

**Comment by helgi** [comment]
Back to the original error after a clean setup but things look screwy so I am going to close this for now while I get a better setup

**Comment by bacongobbler** [comment]
what would be the expected response? 400 BAD REQUEST?

**Comment by jchauncey** [comment]
404

**Comment by helgi** [comment]
Yeah, like @jchauncey said 404 - something is missing. Be it the app or the image.

The API should never be returning a 5xx, even if there is an exception internally

**Comment by arschles** [comment]
IMO we should still return 5xx codes if there was an exception internally. anything else will wind up swallowing an issue that we need to fix.

**Comment by helgi** [comment]
That's what logging is for :) We may need a better way to surface up events and logging information (error and above in the logging module) to operators.

**Comment by arschles** [comment]
I disagree. If one of our components fails and we *only* log it, that's good for an operator, but the user (the person running `deis scale`, `git push`, etc...) gets no feedback on what happened, or even that something went wrong at all.

The best case in that scenario is that they try what they were doing again without telling anyone what happened (because they don't know something happened).

We of course should write robust tests at multiple levels to avoid internal errors, but if they do happen, we should respond with a reasonable 5xx error code and response body instructing the user to tell the applicable operator. Anything less is swallowing (also known as hiding) an error, IMO.
