### ISSUE TITLE
deis-workflow-manager doesn't boot. workflow-dev chart @ 20c052d

### ISSUE THREAD

**Issue by StaymanHou** [deis/workflow#251]
A fresh install using `workflow-dev` chart. `deis-workflow-manager` doesn't boot.
Seems like the deis cluster is still functioning without the manager?

```
➜  ~ kubectl get po --namespace=deis
NAME                          READY     STATUS             RESTARTS   AGE
deis-builder-6c11i            1/1       Running            1          16h
deis-controller-cxx5i         1/1       Running            1          16h
deis-database-4xej5           1/1       Running            0          16h
deis-logger-2xgp5             1/1       Running            0          16h
deis-logger-fluentd-2rp24     1/1       Running            0          16h
deis-logger-fluentd-h7v5i     1/1       Running            0          16h
deis-logger-fluentd-q9e04     1/1       Running            0          16h
deis-logger-fluentd-w1sew     1/1       Running            0          16h
deis-minio-6pcex              1/1       Running            0          16h
deis-monitor-grafana-ylag4    1/1       Running            0          16h
deis-monitor-influxdb-l6wjo   1/1       Running            0          16h
deis-monitor-stdout-s73ko     1/1       Running            0          16h
deis-monitor-telegraf-9b3ah   1/1       Running            0          16h
deis-monitor-telegraf-bwz11   1/1       Running            0          16h
deis-monitor-telegraf-h9xzq   1/1       Running            0          16h
deis-monitor-telegraf-rngv0   1/1       Running            0          16h
deis-registry-wkuyr           1/1       Running            2          16h
deis-router-vr62m             1/1       Running            0          16h
deis-workflow-manager-9hn0p   0/1       CrashLoopBackOff   193        16h
```

```
➜  ~ kubectl logs deis-workflow-manager-9hn0p --namespace=deis
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x651b0d]

goroutine 12 [running]:
panic(0x12456e0, 0xc82000a070)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/deis/workflow-manager/data.getDeisRCItems(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/deis/workflow-manager/data/data.go:153 +0x14d
github.com/deis/workflow-manager/data.InstalledDeisData.Get(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/deis/workflow-manager/data/installed_data.go:29 +0x6b
github.com/deis/workflow-manager/data.(*InstalledDeisData).Get(0xc820248530, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:16 +0xb5
github.com/deis/workflow-manager/data.GetInstalled(0x7f5e8f9c46f0, 0xc820248530, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/deis/workflow-manager/data/data.go:86 +0x75
github.com/deis/workflow-manager/data.GetCluster(0x7f5e8f9c46f0, 0xc820248530, 0x7f5e8f9c34d8, 0xc820258210, 0x7f5e8f9c3510, 0xc820246fa0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/deis/workflow-manager/data/data.go:31 +0x84
github.com/deis/workflow-manager/data.NewAvailableVersionsFromAPI.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/deis/workflow-manager/data/available_versions.go:49 +0x35c
github.com/deis/workflow-manager/data.availableVersionsFromAPI.Refresh(0x0, 0x0, 0x0, 0xc820246f60, 0xc8202581e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/deis/workflow-manager/data/available_versions.go:56 +0x5b
github.com/deis/workflow-manager/data.(*availableVersionsFromAPI).Refresh(0xc8201653c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:4 +0xbe
github.com/deis/workflow-manager/jobs.GetLatestVersionData.Do(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/deis/workflow-manager/jobs/jobs.go:58 +0x84
github.com/deis/workflow-manager/jobs.(*GetLatestVersionData).Do(0xc820246cc0, 0x0, 0x0)
	<autogenerated>:2 +0xa2
github.com/deis/workflow-manager/jobs.runJobs(0xc820246ca0, 0x2, 0x2)
	/go/src/github.com/deis/workflow-manager/jobs/jobs.go:89 +0xbb
github.com/deis/workflow-manager/jobs.DoPeriodic.func1(0xc820246ca0, 0x2, 0x2, 0xc8201650c0, 0xc8201e3800)
	/go/src/github.com/deis/workflow-manager/jobs/jobs.go:72 +0x4a
created by github.com/deis/workflow-manager/jobs.DoPeriodic
	/go/src/github.com/deis/workflow-manager/jobs/jobs.go:82 +0x99
```

**Comment by bacongobbler** [comment]
that would be pointing at this line of code: https://github.com/deis/workflow-manager/blob/86ef470fcc8a912e93f13d315b68701e8985295c/data/data.go#L151-L153

ping @arschles

**Comment by bacongobbler** [comment]
and yes, the cluster will work fine without [workflow-manager](https://github.com/deis/workflow-manager#stay-up-to-date).

**Comment by StaymanHou** [comment]
Thanks for confirming that.

**Comment by bacongobbler** [comment]
@StaymanHou can you please try workflow-dev again? I'm fairly certain that https://github.com/deis/workflow-manager/pull/56 resolved this issue.

**Comment by StaymanHou** [comment]
Yeah, this is resolved. Thanks
