### ISSUE TITLE
deis logs errors because workflow is trying to serialize the log message as json

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow#265]
```
INFO URL:http://10.100.54.102:8088/foo?log_lines=1000
ERROR Internal Server Error: /v2/apps/foo/logs
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/usr/lib/python3.5/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/usr/lib/python3.5/site-packages/rest_framework/response.py", line 71, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/usr/lib/python3.5/site-packages/rest_framework/renderers.py", line 104, in render
    separators=separators
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/site-packages/rest_framework/utils/encoders.py", line 64, in default
    return super(JSONEncoder, self).default(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'2016/01/11 22:16:43 10.244.78.1 GET /\n\n2016/01/11 22:16:43 10.244.78.1 GET /\n\n' is not JSON serializable
10.244.78.1 "GET /v2/apps/foo/logs HTTP/1.1" 500 27 "Deis Client v2.0.0-dev"
```

this just started happening today so Im not sure what could have caused it.

**Comment by jchauncey** [comment]
@helgi @mboersma thoughts?

**Comment by jchauncey** [comment]
Ok reverting commit 934d84f9220debd7b1acd4810e2b6d613c671d99 which is the 3.5 upgrade fixes the issue I am seeing. #110

**Comment by jchauncey** [comment]
ok im going to revert this commit on my branch for now so I can keep working on logging. but can we get this situated soon?

**Comment by bacongobbler** [comment]
Why it's encoding the log messages as JSON is beyond me. We explicitly tell the API view to encode the response as [text/plain](https://github.com/deis/workflow/blob/master/rootfs/api/views.py#L223-L225) so there's something funky going on here.
