### ISSUE TITLE
Not able to scale process

### ISSUE THREAD

**Issue by vdice** [deis/workflow#420]
When attempting to scale a worker process on an app running on GKE via the following steps:

`deis create --no-remote test`
`deis pull deis/example-go:latest -a test --procfile="worker: while true; do echo hi; sleep 3; done"`
`deis ps:scale worker=1 -a test`

the following cli error is produced:

```
Scaling processes... but first, coffee!
Error:
500 Internal Server Error
<h1>Server Error (500)</h1>
```

and the workflow pod logs show:

```
INFO test: config test-3daede4 updated
INFO test: release test-v1 created
INFO [test]: vdice created initial release
10.240.0.6 "POST /v2/apps/ HTTP/1.1" 201 160 "Deis Client v2.0.0-dev"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.240.0.6 "POST /v2/apps/example-go/builds/ HTTP/1.1" 404 23 "Deis Client v2.0.0-dev"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
INFO test: build test-5cf7ccf created
INFO test: release test-v2 created
INFO [test]: vdice deployed deis/example-go:latest
INFO Pulling Docker image deis/example-go:latest
INFO Tagging Docker image deis/example-go:latest as 10.111.255.225:5000/test:v2
INFO Pushing Docker image 10.111.255.225:5000/test:v2
INFO test: vdice scaled containers cmd=1
INFO [test]: vdice scaled containers cmd=1
DEBUG scale test_v2.cmd, img test:v2, params {'tags': {}, 'aname': 'test', 'version': 'v2', 'envs': {}, 'cpu': {}, 'healthcheck': {}, 'memory': {}, 'app_type': 'cmd', 'num': 1, 'build_type': 'deispull'}, cmd ""
DEBUG create test_v2.cmd, img test:v2, params {'tags': {}, 'aname': 'test', 'version': 'v2', 'envs': {}, 'build_type': 'deispull', 'healthcheck': {}, 'memory': {}, 'app_type': 'cmd', 'cpu': {}, 'num': 1}, cmd ""
CRITICAL <Response [201]>
DEBUG scaling RC test-v2-cmd in namespace test from 0 to 1 replicas
DEBUG waiting for RC test-v2-cmd to get a newer resource version than 468536 (30s timeout)
DEBUG RC test-v2-cmd has a new resource version 468537
DEBUG waiting for 1 pods to be processed in test namespace to be known by the k8s api (120s timeout)
DEBUG 1 out of 1 pods to be processed in namespace test were found
DEBUG waiting for 1 pods to get to state Scheduled in test namespace (120s timeout)
DEBUG 1 out of 1 pods in namespace test are in state Scheduled
DEBUG waiting for 1 pods in test namespace to be in services (120s timeout)
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
DEBUG 1 out of 1 pods in namespace test are in service
INFO test: domain test added
INFO [test]: domain test added
10.240.0.6 "POST /v2/apps/test/builds/ HTTP/1.1" 201 266 "Deis Client v2.0.0-dev"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
10.108.2.1 "GET /healthz HTTP/1.1" 200 2 "Go 1.1 package http"
INFO test: vdice scaled containers worker=1
INFO [test]: vdice scaled containers worker=1
DEBUG scale test_v2.worker, img test:v2, params {'tags': {}, 'aname': 'test', 'version': 'v2', 'envs': {}, 'cpu': {}, 'healthcheck': {}, 'memory': {}, 'app_type': 'worker', 'num': 1, 'build_type': 'deispull'}, cmd "bash -c 'while true; do echo hi; sleep 3; done'"
DEBUG create test_v2.worker, img test:v2, params {'tags': {}, 'aname': 'test', 'version': 'v2', 'envs': {}, 'build_type': 'deispull', 'healthcheck': {}, 'memory': {}, 'app_type': 'worker', 'cpu': {}, 'num': 1}, cmd "bash -c 'while true; do echo hi; sleep 3; done'"
DEBUG failed to create Namespace test: 409 Conflict
{'reason': 'AlreadyExists', 'code': 409, 'metadata': {}, 'message': 'namespaces "test" already exists', 'apiVersion': 'v1', 'kind': 'Status', 'details': {'kind': 'namespaces', 'name': 'test'}, 'status': 'Failure'}
ERROR test: test_v2.worker (scale): failed to get ReplicationController "test-v2-worker" in Namespace "test": 404 Not Found
{'reason': 'NotFound', 'code': 404, 'metadata': {}, 'message': 'replicationControllers "test-v2-worker" not found', 'apiVersion': 'v1', 'kind': 'Status', 'details': {'kind': 'replicationControllers', 'name': 'test-v2-worker'}, 'status': 'Failure'}
ERROR [test]: test_v2.worker (scale): failed to get ReplicationController "test-v2-worker" in Namespace "test": 404 Not Found
{'reason': 'NotFound', 'code': 404, 'metadata': {}, 'message': 'replicationControllers "test-v2-worker" not found', 'apiVersion': 'v1', 'kind': 'Status', 'details': {'kind': 'replicationControllers', 'name': 'test-v2-worker'}, 'status': 'Failure'}
ERROR Internal Server Error: /v2/apps/test/scale/
Traceback (most recent call last):
  File "/app/scheduler/__init__.py", line 387, in create
    self._create_namespace(app_name)
  File "/app/scheduler/__init__.py", line 584, in _create_namespace
    error(resp, "create Namespace {}".format(app_name))
  File "/app/scheduler/__init__.py", line 274, in error
    raise KubeException(errmsg, response=resp)
scheduler.KubeException: failed to create Namespace test: 409 Conflict
{'reason': 'AlreadyExists', 'code': 409, 'metadata': {}, 'message': 'namespaces "test" already exists', 'apiVersion': 'v1', 'kind': 'Status', 'details': {'kind': 'namespaces', 'name': 'test'}, 'status': 'Failure'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 233, in scale
    app.scale(request.user, new_structure)
  File "/app/api/models/app.py", line 280, in scale
    self._scale_containers(scale_types, to_remove)
  File "/app/api/models/app.py", line 323, in _scale_containers
    **kwargs
  File "/app/scheduler/__init__.py", line 360, in scale
    self.create(name, image, command, **kwargs)
  File "/app/scheduler/__init__.py", line 399, in create
    self._scale_rc(name, app_name, 0)
  File "/app/scheduler/__init__.py", line 717, in _scale_rc
    rc = self._get_rc(name, namespace)
  File "/app/scheduler/__init__.py", line 622, in _get_rc
    error(resp, 'get ReplicationController "{}" in Namespace "{}"', name, namespace)
  File "/app/scheduler/__init__.py", line 274, in error
    raise KubeException(errmsg, response=resp)
scheduler.KubeException: failed to get ReplicationController "test-v2-worker" in Namespace "test": 404 Not Found
{'reason': 'NotFound', 'code': 404, 'metadata': {}, 'message': 'replicationControllers "test-v2-worker" not found', 'apiVersion': 'v1', 'kind': 'Status', 'details': {'kind': 'replicationControllers', 'name': 'test-v2-worker'}, 'status': 'Failure'}
10.240.0.6 "POST /v2/apps/test/scale/ HTTP/1.1" 500 27 "Deis Client v2.0.0-dev"
```

**Comment by helgi** [comment]
What is the expected behaviour here? I see two options

1. `deis scale worker=1` has to be called before the worker comes into existance
2. We pick up `worker` type from `procfile` and right away give it scale of `1` - Right now our defaults for scale types do not account for that

**Comment by bacongobbler** [comment]
Option 2 should be the expected outcome. When in doubt, follow Heroku's example. :)

**Comment by helgi** [comment]
Option 1 is the Heroku example, actually - Over there `web` (the default, not `cmd`) is the only one that auto starts. 

Option 2 is how most people would expect it I imagine when defining types in a Procfile.

**Comment by krancour** [comment]
Some more datapoints for consideration.

I just ran into this same issue with a buildpack app as well (example-go).  Putting aside the question of whether all process types should or should not autostart with scale=1, I was actually unable to manually start any process type that wasn't the default _at all_.

That seems like an issue of showstopper magnitude.
