### ISSUE TITLE
Error starting workflow

### ISSUE THREAD

**Issue by aledbf** [deis/workflow#438]
How I can trace this error?

```
$ kubectl  logs -f deis-workflow-2sn3q --namespace deis
system information:
Django Version: 1.9.2
Python 3.5.1
Django checks:
System check identified no issues (2 silenced).
Health Checks:
Checking if database is alive
Database is alive!
Database Migrations:
Operations to perform:
  Apply all migrations: guardian, authtoken, auth, contenttypes, sessions, api
Running migrations:
  No migrations to apply.
[2016-03-01 17:00:10 +0000] [43] [INFO] Starting gunicorn 19.4.5
[2016-03-01 17:00:10 +0000] [43] [INFO] Listening at: http://0.0.0.0:8000 (43)
[2016-03-01 17:00:10 +0000] [43] [INFO] Using worker: sync
[2016-03-01 17:00:10 +0000] [47] [INFO] Booting worker with pid: 47
[2016-03-01 17:00:10 +0000] [48] [INFO] Booting worker with pid: 48
[2016-03-01 17:00:11 +0000] [56] [INFO] Booting worker with pid: 56
[2016-03-01 17:00:11 +0000] [62] [INFO] Booting worker with pid: 62
[2016-03-01 17:00:11 +0000] [67] [INFO] Booting worker with pid: 67
[2016-03-01 17:00:11 +0000] [69] [INFO] Booting worker with pid: 69
[2016-03-01 17:00:11 +0000] [71] [INFO] Booting worker with pid: 71
[2016-03-01 17:00:11 +0000] [74] [INFO] Booting worker with pid: 74
[2016-03-01 17:00:11 +0000] [75] [INFO] Booting worker with pid: 75
[2016-03-01 17:00:11 +0000] [76] [INFO] Booting worker with pid: 76
[2016-03-01 17:00:11 +0000] [78] [INFO] Booting worker with pid: 78
[2016-03-01 17:00:11 +0000] [88] [INFO] Booting worker with pid: 88
[2016-03-01 17:00:11 +0000] [104] [INFO] Booting worker with pid: 104
[2016-03-01 17:00:11 +0000] [106] [INFO] Booting worker with pid: 106
[2016-03-01 17:00:11 +0000] [113] [INFO] Booting worker with pid: 113
Publishing DB state to k8s...
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/jsonfield/fields.py", line 79, in pre_init
    return json.loads(value, **self.load_kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 17 (char 16)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/api/management/commands/load_db_state_to_k8s.py", line 14, in handle
    for obj in model.objects.all():
  File "/usr/lib/python3.5/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/usr/lib/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python3.5/site-packages/django/db/models/query.py", line 69, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/usr/lib/python3.5/site-packages/django/db/models/base.py", line 452, in from_db
    new = cls(*values)
  File "/usr/lib/python3.5/site-packages/django/db/models/base.py", line 373, in __init__
    setattr(self, field.attname, val)
  File "/usr/lib/python3.5/site-packages/jsonfield/subclassing.py", line 41, in __set__
    obj.__dict__[self.field.name] = self.field.pre_init(value, obj)
  File "/usr/lib/python3.5/site-packages/jsonfield/fields.py", line 81, in pre_init
    raise ValidationError(_("Enter valid JSON"))
django.core.exceptions.ValidationError: ['Enter valid JSON']
```

**Comment by mboersma** [comment]
Probably there is invalid JSON somehow stored in one of the relevant columns. This is a Django management command that is run during startup: load_db_state_to_k8s.py. There are JSONFields in both `App` and `Config`, so it's probably a row for one of those models.

You could enter the deis/workflow container and run `manage.py dbshell` to poke around the database, or `manage.py shell` to load the objects in the Python ORM, which might narrow it down.

**Comment by aledbf** [comment]
@mboersma this error started after an update to current master.

> You could enter the deis/workflow container

I cannot do this because the container is restarted (failure in healthcheck)

**Comment by helgi** [comment]
Do you have an idea from when you were updating from

**Comment by aledbf** [comment]
@mboersma Is possible to check this in other way? (I have more than 12000 builds, so checking one by one is not an an option :) )

**Comment by helgi** [comment]
You could write a very little python script that connects to the DB, loops through the given rows in the affected tables and do a `json.loads()` to find the affected rows.

The `App` model is simple to check since there is only JSONField per app, `structures` field

Other option is to pull Config or App out of https://github.com/deis/workflow/blob/master/rootfs/api/management/commands/load_db_state_to_k8s.py#L13 and see which one makes your workflow start but then your data is still broken

Maybe we can figure out a small script for you to run if all else fail so we can get to the bottom of it

That being said, within the alpha / beta we are not guaranteeing that workflow can be upgraded, especially if you started out with a v1 world, at least yet :)

**Comment by aledbf** [comment]
I found the rows (2) with the issue.
This is the small script (node.js) to check with row contains the error

```
var fs = require('fs');

fs.readFileSync(process.argv[2]).toString().split(/\r?\n/).forEach(function(line) {
    try {
      JSON.parse(line);
    }catch (e) {
      console.log("Error: '" + line + "': " + e);
    }
});
```

node ^^ <path to file with column>

Thanks @mboersma @helgi

**Comment by helgi** [comment]
@aledbf Ah perfect :-) Glad it was that easy. Do you know if those were new or old records?

**Comment by aledbf** [comment]
@helgi I found that this happened in 2 builds that use `deis pull -p '{"web":1, "cron"1}'` so I think the specified json object is not being verified

**Comment by mboersma** [comment]
> I think the specified json object is not being verified

Good catch--let's enter a bug for `deis pull` possibly allowing unvalidated JSON through into the...`App` model?

**Comment by helgi** [comment]
Yeah that should be a ticket - So the `p` is suppose to be YAML but the more I think about it I don't think we verify procfiles, but we do verify app structures (or try to)
