### ISSUE TITLE
Go stack traces on helmc uninstall

### ISSUE THREAD

**Issue by olalonde** [deis/workflow#567]
```
$ helmc uninstall workflow-${PREVIOUS_WORKFLOW_RELEASE} -n deis
[WARN] Could not delete Service deis-monitor-influxui (Skipping): exit status 2
---> failed MSpanList_Insert 0x1c98378 0x7a8765872c5b 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x1a56670, 0x1c98378)
        /usr/src/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x1a56600, 0x1, 0x1000000000a, 0xcf29)
        /usr/src/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x1a5da78, 0x1c98448)
        /usr/src/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x1c7e000, 0xa, 0x1c98448)
        /usr/src/go/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
        /usr/src/go/src/runtime/asm_amd64.s:198 fp=0xc2081e7950 sp=0xc2081e7948
runtime.mallocgc(0x90, 0xd80380, 0x1, 0xc208105ef0)
        /usr/src/go/src/runtime/malloc.go:178 +0x849 fp=0xc2081e7a00 sp=0xc2081e7950
runtime.newarray(0xd80380, 0x11, 0xc208105ef0)
        /usr/src/go/src/runtime/malloc.go:365 +0xc1 fp=0xc2081e7a38 sp=0xc2081e7a00
runtime.makeslice(0x11c5320, 0x11, 0x11, 0x0, 0x0, 0x0)
        /usr/src/go/src/runtime/slice.go:32 +0x15c fp=0xc2081e7a80 sp=0xc2081e7a38
math/big.nat.divLarge(0xc20805f180, 0x10, 0x25, 0xc2081bea20, 0x20, 0x24, 0xc2081beb40, 0x20, 0x24, 0xc2080a6a50, ...)
        /usr/src/go/src/math/big/nat.go:541 +0x2d0 fp=0xc2081e7c18 sp=0xc2081e7a80
math/big.nat.div(0xc20805f180, 0x10, 0x25, 0xc2081bea20, 0x20, 0x24, 0xc2081beb40, 0x20, 0x24, 0xc2080a6a50, ...)
        /usr/src/go/src/math/big/nat.go:519 +0x35a fp=0xc2081e7cc0 sp=0xc2081e7c18
math/big.nat.expNNWindowed(0xc2081beb40, 0x20, 0x24, 0xc2081c7400, 0x10, 0x14, 0xc2081c72c0, 0x10, 0x14, 0xc2080a6a50, ...)
        /usr/src/go/src/math/big/nat.go:1372 +0x82a fp=0xc2081e7f50 sp=0xc2081e7cc0
math/big.nat.expNN(0xc20805f180, 0x10, 0x25, 0xc2081c7400, 0x10, 0x14, 0xc2081c72c0, 0x10, 0x14, 0xc2080a6a50, ...)
        /usr/src/go/src/math/big/nat.go:1260 +0x4b0 fp=0xc2081e80e8 sp=0xc2081e7f50
math/big.nat.probablyPrime(0xc2080a6a50, 0x10, 0x15, 0x14, 0x0)
        /usr/src/go/src/math/big/nat.go:1445 +0x887 fp=0xc2081e8260 sp=0xc2081e80e8
math/big.(*Int).ProbablyPrime(0xc208201d00, 0x14, 0xc207fec106)
        /usr/src/go/src/math/big/int.go:741 +0x4a fp=0xc2081e8290 sp=0xc2081e8260
crypto/rsa.(*PrivateKey).Validate(0xc208040d80, 0x0, 0x0)
        /usr/src/go/src/crypto/rsa/rsa.go:110 +0x108 fp=0xc2081e8390 sp=0xc2081e8290
crypto/x509.ParsePKCS1PrivateKey(0xc208220a00, 0x4a7, 0x4a7, 0xc208040d80, 0x0, 0x0)
        /usr/src/go/src/crypto/x509/pkcs1.go:77 +0x702 fp=0xc2081e8518 sp=0xc2081e8390
crypto/tls.parsePrivateKey(0xc208220a00, 0x4a7, 0x4a7, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/crypto/tls/tls.go:259 +0x7d fp=0xc2081e8608 sp=0xc2081e8518
crypto/tls.X509KeyPair(0xc2080b5530, 0x0, 0x0, 0xc2081d2e76, 0x0, 0x0, 0xc208201ca0, 0x1, 0x1, 0x0, ...)
        /usr/src/go/src/crypto/tls/tls.go:213 +0x394 fp=0xc2081e8800 sp=0xc2081e8608
k8s.io/kubernetes/pkg/client/transport.TLSConfigFor(0xc2080a00e0, 0xc20809e960, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/transport.go:76 +0x2c0 fp=0xc2081e8960 sp=0xc2081e8800
k8s.io/kubernetes/pkg/client/transport.(*tlsTransportCache).get(0x1a3de60, 0xc2080a00e0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/cache.go:53 +0x1f9 fp=0xc2081e89f8 sp=0xc2081e8960
k8s.io/kubernetes/pkg/client/transport.New(0xc2080a00e0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/transport.go:43 +0x149 fp=0xc2081e8a58 sp=0xc2081e89f8
k8s.io/kubernetes/pkg/client/restclient.TransportFor(0xc208202000, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/transport.go:36 +0x5a fp=0xc2081e8a88 sp=0xc2081e8a58
k8s.io/kubernetes/pkg/client/restclient.RESTClientFor(0xc208202000, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/config.go:145 +0x19b fp=0xc2081e8b38 sp=0xc2081e8a88
k8s.io/kubernetes/pkg/client/unversioned.New(0xc20805fe00, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/helper.go:49 +0xe2 fp=0xc2081e8c28 sp=0xc2081e8b38
k8s.io/kubernetes/pkg/client/unversioned.NegotiateVersion(0x0, 0xc20805fe00, 0xc208201200, 0xc208066a00, 0x7, 0x8, 0xc2081f84e0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/helper.go:125 +0x75 fp=0xc2081e8ea0 sp=0xc2081e8c28
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ClientCache).ClientConfigForVersion(0xc208035fc0, 0xc2081fa5e0, 0xc2081fa5e0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/clientcache.go:76 +0x2f1 fp=0xc2081e90b8 sp=0xc2081e8ea0
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ClientCache).ClientForVersion(0xc208035fc0, 0xc2081fa5e0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/clientcache.go:103 +0xbc fp=0xc2081e9128 sp=0xc2081e90b8
k8s.io/kubernetes/pkg/kubectl/cmd/util.func·004(0xc208011650, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:237 +0x150 fp=0xc2081e9248 sp=0xc2081e9128
k8s.io/kubernetes/pkg/kubectl/resource.ClientMapperFunc.ClientForMapping(0xc208149b10, 0xc208011650, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/interfaces.go:45 +0x51 fp=0xc2081e9278 sp=0xc2081e9248
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).visitorResult(0xc208196f70, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:627 +0x2c27 fp=0xc2081e99a8 sp=0xc2081e9278
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).Do(0xc208196f70, 0x1a4c900)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:686 +0x33 fp=0xc2081e9aa0 sp=0xc2081e99a8
k8s.io/kubernetes/pkg/kubectl/cmd.RunDelete(0xc20814ab40, 0x1c8fff0, 0xc20804e008, 0xc20819d400, 0xc2081a9a40, 0x2, 0x3, 0xc2080af7c0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:119 +0x4d0 fp=0xc2081e9c10 sp=0xc2081e9aa0
k8s.io/kubernetes/pkg/kubectl/cmd.func·020(0xc20819d400, 0xc2081a9a40, 0x2, 0x3)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:87 +0xd3 fp=0xc2081e9ca0 sp=0xc2081e9c10
github.com/spf13/cobra.(*Command).execute(0xc20819d400, 0xc2081a99b0, 0x3, 0x3, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f fp=0xc2081e9db8 sp=0xc2081e9ca0
github.com/spf13/cobra.(*Command).ExecuteC(0xc208063600, 0xc20819d400, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db fp=0xc2081e9ec8 sp=0xc2081e9db8
github.com/spf13/cobra.(*Command).Execute(0xc208063600, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a fp=0xc2081e9ef0 sp=0xc2081e9ec8
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0x101 fp=0xc2081e9f70 sp=0xc2081e9ef0
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x2f fp=0xc2081e9f98 sp=0xc2081e9f70
runtime.main()
        /usr/src/go/src/runtime/proc.go:63 +0xf3 fp=0xc2081e9fe0 sp=0xc2081e9f98
runtime.goexit()
        /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2081e9fe8 sp=0xc2081e9fe0

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1a3f640)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 13 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

[WARN] Could not delete Service deis-nsqd (Skipping): exit status 2
---> failed MSpanList_Insert 0x1c82000 0x7a876641ebac 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x1a22f8b)
        /usr/src/go/src/runtime/panic.go:491 +0xad fp=0x7fff5fbfe490 sp=0x7fff5fbfe460
runtime.MSpanList_Insert(0x1a59a08, 0x1c82000)
        /usr/src/go/src/runtime/mheap.c:692 +0x8f fp=0x7fff5fbfe4b8 sp=0x7fff5fbfe490
MHeap_FreeSpanLocked(0x1a56600, 0x1c82000, 0x100)
        /usr/src/go/src/runtime/mheap.c:583 +0x163 fp=0x7fff5fbfe4f8 sp=0x7fff5fbfe4b8
MHeap_Grow(0x1a56600, 0x8, 0x0)
        /usr/src/go/src/runtime/mheap.c:420 +0x1a8 fp=0x7fff5fbfe538 sp=0x7fff5fbfe4f8
MHeap_AllocSpanLocked(0x1a56600, 0x1, 0x0)
        /usr/src/go/src/runtime/mheap.c:298 +0x365 fp=0x7fff5fbfe578 sp=0x7fff5fbfe538
mheap_alloc(0x1a56600, 0x1, 0x12, 0x0)
        /usr/src/go/src/runtime/mheap.c:190 +0x121 fp=0x7fff5fbfe5a0 sp=0x7fff5fbfe578
runtime.MHeap_Alloc(0x1a56600, 0x1, 0x10000000012, 0xcf29)
        /usr/src/go/src/runtime/mheap.c:240 +0x66 fp=0x7fff5fbfe5d8 sp=0x7fff5fbfe5a0
MCentral_Grow(0x1a5e378, 0x0)
        /usr/src/go/src/runtime/mcentral.c:197 +0x8b fp=0x7fff5fbfe640 sp=0x7fff5fbfe5d8
runtime.MCentral_CacheSpan(0x1a5e378, 0x0)
        /usr/src/go/src/runtime/mcentral.c:85 +0x167 fp=0x7fff5fbfe678 sp=0x7fff5fbfe640
runtime.MCache_Refill(0x1c7e000, 0x12, 0x0)
        /usr/src/go/src/runtime/mcache.c:90 +0xa0 fp=0x7fff5fbfe6a0 sp=0x7fff5fbfe678
runtime.mcacheRefill_m()
        /usr/src/go/src/runtime/malloc.c:368 +0x57 fp=0x7fff5fbfe6c0 sp=0x7fff5fbfe6a0
runtime.onM(0x153e028)
        /usr/src/go/src/runtime/asm_amd64.s:273 +0x9a fp=0x7fff5fbfe6c8 sp=0x7fff5fbfe6c0
runtime.mallocgc(0x120, 0x11b60c0, 0x0, 0x0)
```

```
$ helmc --version
helmc version 0.8.1+a9c55cf
$ deis --version
v2.4.0
```

**Comment by olalonde** [comment]
Ah, I just noticed that I'm getting those with kubernetes as well

```
$ kd get po
failed MSpanList_Insert 0x1c85d58 0x7aad89029ee3 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x1a567a8, 0x1c85d58)
```

**Comment by olalonde** [comment]
Fixed by upgrading `kubectl` to http://dl.k8s.io/release/v1.4.1/bin/darwin/amd64/kubectl

See https://github.com/kubernetes/minikube/issues/677
