### ISSUE TITLE
deis pull Error: image myapp:git-b824232 not found

### ISSUE THREAD

**Issue by olalonde** [deis/workflow#583]
I'm having trouble deploying an image to one of my apps with `deis pull`:

```
INFO [myapp]: waited 30s and 1 pods are in service
INFO [myapp]: waited 30s and 1 pods are in service
INFO [myapp]: waited 30s and 4 pods are in service
INFO [myapp]: waited 40s and 4 pods are in service
INFO [myapp]: waited 50s and 4 pods are in service
ERROR [myapp]: (app::deploy): There was a problem deploying v75. Rolling back process types to release v74.
There was a problem while deploying v75 of myapp-web. Additional information:
[Error: image myapp:git-b824232 not found, Error: image myapp:git-b824232 not found]
ERROR:root:(app::deploy): There was a problem deploying v75. Rolling back process types to release v74.
There was a problem while deploying v75 of myapp-web. Additional information:
[Error: image myapp:git-b824232 not found, Error: image myapp:git-b824232 not found]
Traceback (most recent call last):
  File "/app/scheduler/__init__.py", line 266, in deploy
    namespace, name, image, entrypoint, command, **kwargs
  File "/app/scheduler/resources/deployment.py", line 138, in update
    self.wait_until_ready(namespace, name, **kwargs)
  File "/app/scheduler/resources/deployment.py", line 338, in wait_until_ready
    additional_timeout = self.pod._handle_pending_pods(namespace, labels)
  File "/app/scheduler/resources/pod.py", line 560, in _handle_pending_pods
    self._handle_pod_errors(pod, reason, message)
  File "/app/scheduler/resources/pod.py", line 499, in _handle_pod_errors
    raise KubeException(message)
scheduler.exceptions.KubeException: [Error: image myapp:git-b824232 not found, Error: image myapp:git-b824232 not found]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/app.py", line 499, in deploy
    async_run(tasks)
  File "/app/api/utils.py", line 169, in async_run
    raise error
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/app/api/utils.py", line 182, in async_task
    yield from loop.run_in_executor(None, params)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/scheduler/__init__.py", line 272, in deploy
    ) from e
scheduler.exceptions.KubeException: There was a problem while deploying v75 of myapp-web. Additional information:
[Error: image myapp:git-b824232 not found, Error: image myapp:git-b824232 not found]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/app.py", line 508, in deploy
    raise DeisException('{}\n{}'.format(err, str(e))) from e
api.exceptions.DeisException: There was a problem deploying v75. Rolling back process types to release v74.
There was a problem while deploying v75 of myapp-web. Additional information:
[Error: image myapp:git-b824232 not found, Error: image myapp:git-b824232 not found]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/api/models/build.py", line 64, in create
    self.app.deploy(new_release)
  File "/app/api/models/app.py", line 516, in deploy
    raise ServiceUnavailable(err) from e
api.exceptions.ServiceUnavailable: (app::deploy): There was a problem deploying v75. Rolling back process types to release v74.
There was a problem while deploying v75 of myapp-web. Additional information:
[Error: image myapp:git-b824232 not found, Error: image myapp:git-b824232 not found]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 181, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 258, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 78, in create
    raise DeisException(str(e)) from e
api.exceptions.DeisException: (app::deploy): There was a problem deploying v75. Rolling back process types to release v74.
There was a problem while deploying v75 of myapp-web. Additional information:
[Error: image myapp:git-b824232 not found, Error: image myapp:git-b824232 not found]
10.244.0.3 "POST /v2/apps/myapp/builds/ HTTP/1.1" 400 288 "Deis Client v2.7.1"
```

I'm not sure why it is now failing as I had no trouble deploying for the past few days. I'm using a private AWS ECR registry (configured with `deis registry:set` before the deployment). The `myapp:git-b824232` image does exist in my registry.

**Comment by kmala** [comment]
Can you check if the imagepullsecret is present and if its correct `kubectl get secret private-registry --namespace <app> -o yaml`

**Comment by bacongobbler** [comment]
Three things come to mind:

1) @kmala's comment above, which can be attributed to...
2) https://github.com/deis/registry-token-refresher is failing and not refreshing the short-lived token you supplied. Or...
3) network connection between kubernetes and ECR is (temporarily?) broken.

Check those things out and let us know the results of your findings :)

**Comment by olalonde** [comment]
Secret command returns a something like this:

```yaml
apiVersion: v1
data:
  .dockerconfigjson: # is this supposed to be the registry password? because it's wrong
kind: Secret
metadata:
  creationTimestamp: 2016-10-24T04:08:14Z
  labels:
    app: myapp
    heritage: deis
  name: private-registry
  namespace: myapp
  resourceVersion: "3046572"
  selfLink: /api/v1/namespaces/myapp/secrets/private-registry
  uid: 7c3c4d47-999f-11e6-a5e2-068755380eff
type: kubernetes.io/dockerconfigjson
```

@bacongobbler this app is using an external registry but I'm still using the internal deis registry for the platform. Isn't https://github.com/deis/registry-token-refresher if you are using an external registry for the platform?

**Comment by kmala** [comment]
try doing a base64decode of the .dockerconfigjson which gives you a json containing your hostname and auth(base64 encode of username:password).
can you check if they all are hostname, username and password are correct? If they are then there shouldn't be an issue also you check that the current registry config is correct using `deis registry`

**Comment by olalonde** [comment]
Thanks. I'm getting:

```
{"auths": {"<my account id>.dkr.ecr.us-west-1.amazonaws.com": {"auth": <some long base64 encoded string>}}}
```

After decoding the string, I'm getting:

```
AWS:<my aws password/token>
```

So it seems like the registry is correctly configured. `deis registy -a myapp` also returns the correct username/password.

**Comment by olalonde** [comment]
I noticed something curious in the k8s events:

```
2016-10-27 12:44:23 -0700 PDT   2016-10-27 12:44:23 -0700 PDT   1         myapp-web-3724852343-dyff7   Pod       spec.containers{myapp-web}   Normal    Pulling   {kubelet ip-172-20-0-83.us-west-1.compute.internal}   pulling image "myapp:git-b824232"
2016-10-27 12:44:24 -0700 PDT   2016-10-27 12:44:24 -0700 PDT   1         myapp-web-3724852343-dyff7   Pod       spec.containers{myapp-web}   Warning   Failed    {kubelet ip-172-20-0-83.us-west-1.compute.internal}   Failed to pull image "myapp:git-b824232": Error: image library/myapp:git-b824232 not found
2016-10-27 12:44:24 -0700 PDT   2016-10-27 12:44:24 -0700 PDT   1         myapp-web-3724852343-dyff7   Pod       Warning   FailedSync   {kubelet ip-172-20-0-83.us-west-1.compute.internal}   Error syncing pod, skipping: failed to "StartContainer" for "myapp-web" with ErrImagePull: "Error: image library/myapp:git-b824232 not found"
2016-10-27 12:44:25 -0700 PDT   2016-10-27 12:44:25 -0700 PDT   1         myapp-web-3724852343-dyff7   Pod       spec.containers{myapp-web}   Normal    BackOff   {kubelet ip-172-20-0-83.us-west-1.compute.internal}   Back-off pulling image "myapp:git-b824232"
2016-10-27 12:44:25 -0700 PDT   2016-10-27 12:44:25 -0700 PDT   1         myapp-web-3724852343-dyff7   Pod       Warning   FailedSync   {kubelet ip-172-20-0-83.us-west-1.compute.internal}   Error syncing pod, skipping: failed to "StartContainer" for "myapp-web" with ImagePullBackOff: "Back-off pulling image \"myapp:git-b824232\""
```

This part: `ErrImagePull: "Error: image library/myapp:git-b824232 not found"`

What's `library/`? Does it thing it's an official docker hub image?

**Comment by bacongobbler** [comment]
Yes, that would indicate it's attempting to pull from DockerHub.

**Comment by olalonde** [comment]
Oops, I did a deis pull without the registry URL by accident. But still same issue.

```
2016-10-27 13:01:33 -0700 PDT   2016-10-27 13:01:01 -0700 PDT   2         myapp-web-3937323748-r6qzn   Pod       spec.containers{myapp-web}   Warning   Failed    {kubelet ip-172-20-0-147.us-west-1.compute.internal}   Failed to pull image "<MY_ACCOUNT_ID>.dkr.ecr.us-west-1.amazonaws.com/myapp:git-b824232": [Error: image myapp:git-b824232 not found, Error: image myapp:git-b824232 not found]
2016-10-27 13:01:33 -0700 PDT   2016-10-27 13:01:01 -0700 PDT   2         myapp-web-3937323748-r6qzn   Pod                 Warning   FailedSync   {kubelet ip-172-20-0-147.us-west-1.compute.internal}   Error syncing pod, skipping: failed to "StartContainer" for "myapp-web" with ErrImagePull: "[Error: image myapp:git-b824232 not found, Error: image myapp:git-b824232 not found]"
```

If I do a local `docker pull "<MY_ACCOUNT_ID>.dkr.ecr.us-west-1.amazonaws.com/myapp:git-b824232"`

**Comment by olalonde** [comment]
```
~$ docker pull "<MY_ACCOUNT_ID>.dkr.ecr.us-west-1.amazonaws.com/myapp:git-b824232"
git-b824232: Pulling from myapp

43c265008fae: Already exists
af36d2c7a148: Already exists
143e9d501644: Already exists
f6a5aab6cd0c: Already exists
1e2b64ecebce: Already exists
1caa7461f802: Already exists
a1a1a959f279: Already exists
7e688dad4eeb: Already exists
a3ed95caeb02: Already exists
75d6d0daa89f: Already exists
5dcd99cd746d: Already exists
65a99ccb9423: Already exists
624bccc962fc: Already exists
47f1fe373e3f: Already exists
4aafe9aa5cb7: Already exists
9cf29daf4ff6: Already exists
365f337792df: Already exists
d94f06921328: Already exists
ec3f28ac7b20: Already exists
Digest: sha256:c9474d969b1d06c492b9c8a0ef828810743c078e49b736856bbf6578d003036d
Status: Image is up to date for <MY_ACCOUNT_ID>.dkr.ecr.us-west-1.amazonaws.com/myapp:git-b824232
```

I just wish the logs were a bit more verbose about why it fails :(

**Comment by kmala** [comment]
are you sure the creds you are using are still valid.can you compare your local ~/.dockerconfig with the ones in the secret/`deis registry` outputs.

**Comment by olalonde** [comment]
@kmala yes, I made sure they are the same

even wrote a script for it to be sure lol :)

```
#!/usr/bin/env bash
pass1=$(
  kubectl get secret private-registry --namespace blockai-api -o yaml \
  | grep .dockerconfigjson \
  | head -n 1 \
  | cut -d " " -f 4 \
  | base64 --decode \
  | jq '.auths' \
  | jq 'to_entries' \
  | jq '.[0].value.auth' -r \
  | base64 --decode \
  | cut -d ":" -f 2
)
pass2=$(deis registry | grep password | tr -s " " " " | cut -d " " -f2)

echo $pass1
echo $pass2
[ "${pass1}" == "${pass2}" ] && echo "Same pass!"
```

**Comment by kmala** [comment]
this means that deis is creating the secrets correctly 😉 one last thing would be that pass/creds have the permissions. can you check your local one and deis one is same.

**Comment by olalonde** [comment]
I just logged in docker with the credentials listed by `deis registry` and did a docker pull for that image without problem. The frustrating thing `deis pull` used to work just fine a few hours ago. :(

**Comment by olalonde** [comment]
Could this be a disk space issue? It seems like my minion's disks are getting full after a few deployments.

**Comment by olalonde** [comment]
Yep, that was it. I just ran: `docker rm $(docker ps -qa --no-trunc --filter "status=exited")` and `docker rmi $(docker images --filter "dangling=true" -q --no-trunc)` on one of my minions and the `deis pull` is working fine now. On a related note, does deis ever delete old images and containers from minions? Almost all problems I have with K8s and deis end up being related to disk space :(
