### ISSUE TITLE
`deis destroy` generates 500 error

### ISSUE THREAD

**Issue by mboersma** [deis/workflow#64]
Testing Deis v2 alpha with a `deis pull` app gave me an error on `deis destroy`:
```python
DEBUG destroy ribbed-asteroid_v2.cmd.1
ERROR ribbed-asteroid: aborting, failed to destroy some containers
ERROR [ribbed-asteroid]: aborting, failed to destroy some containers
WARNING ribbed-asteroid: Error deleting existing application logs: HTTPConnectionPool(host='127.0.0.1', port=8088): Max retries exceeded with url: /ribbed-asteroid/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f31af2e3350>: Failed to establish a new connection: [Errno 111] Connection refused',))
WARNING [ribbed-asteroid]: Error deleting existing application logs: HTTPConnectionPool(host='127.0.0.1', port=8088): Max retries exceeded with url: /ribbed-asteroid/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f31af2e3350>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR Internal Server Error: /v2/apps/ribbed-asteroid/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 85, in destroy
    self.perform_destroy(instance)
  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 89, in perform_destroy
    instance.delete()
  File "/app/api/models.py", line 223, in delete
    return super(App, self).delete(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 695, in delete
    collector.delete()
  File "/usr/lib/python2.7/site-packages/django/db/models/deletion.py", line 282, in delete
    sender=model, instance=obj, using=self.using
  File "/usr/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/app/api/models.py", line 1165, in _etcd_purge_config
    prevExist=True, dir=True, recursive=True)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 389, in delete
    self.key_endpoint + key, self._MDELETE, params=kwds)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 582, in api_execute
    return self._handle_server_response(response)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 598, in _handle_server_response
    etcd.EtcdError.handle(**r)
  File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 142, in handle
    raise exc(msg)
Exception: Raft Internal Error : etcdserver: request timed out
10.246.43.1 "DELETE /v2/apps/ribbed-asteroid/ HTTP/1.1" 500 27 "Deis Client v1.13.0-dev"
```
`kubectl` shows that the Namespace (and therefore associated Services, RCs, and Pods) was actually deleted.

**Comment by bacongobbler** [comment]
I'll take a look into this!

**Comment by helgi** [comment]
First I created an app and did `deis pull`

```
deis create --no-remote
Creating Application... done, created madras-wayfarer
remote available at ssh://git@10.3.0.182.xip.io:2222/madras-wayfarer.git
deis pull deis/example-go -p "web: example-go" -a madras-wayfarer
```

Here is the destroy

```
deis destroy -a madras-wayfarer
 !    WARNING: Potentially Destructive Action
 !    This command will destroy the application: madras-wayfarer
 !    To proceed, type "madras-wayfarer" or re-run this command with --confirm=madras-wayfarer

> madras-wayfarer
Destroying madras-wayfarer...
done in 0s
```

**Comment by bacongobbler** [comment]
I wasn't able to reproduce this issue either. Demoting from being a showstopper, but still something we should take a look into.

**Comment by helgi** [comment]
Closing since it was an etcd problem
