### ISSUE TITLE
Internal Server Error when running 'deis create --no-remote'

### ISSUE THREAD

**Issue by kwtalley** [deis/workflow#793]
Just deployed deis 2.13.0 on bare metal k8s 1.6. All pods are running and I'm exposing the router via NodePort and a manual 'ExternalIP' as loadbalancer is not an option on bare-metal. Routing seems to be correct as I'm able to curl the api endpoint and get the correct error message `{"detail":"Authentication credentials were not provided."}`

When trying to create the test app with `deis create --no-remote` i'm getting the following from the controller:

```
172.16.254.216 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.13.0"
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/app/api/models/app.py", line 89, in save
    self.release_set.latest()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 550, in latest
    return self._earliest_or_latest(field_name=field_name, direction="-")
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 544, in _earliest_or_latest
    return obj.get()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
api.models.release.DoesNotExist: Release matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 20, in perform_create
    obj = serializer.save(owner=self.request.user)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 906, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/api/models/app.py", line 92, in save
    if self._scheduler.ns.get(self.id).status_code == 200:
  File "/app/scheduler/resources/namespace.py", line 22, in get
    response = self.http_get(url, params=self.query_params(**kwargs))
  File "/app/scheduler/__init__.py", line 171, in http_get
    response = self.session.get(url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 333, in connect
    cert = self.sock.getpeercert()
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 343, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 219, in get_subj_alt_name
    for name in ext.get_values_for_type(x509.DNSName)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 219, in <listcomp>
    for name in ext.get_values_for_type(x509.DNSName)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 175, in _dnsname_to_stdlib
    name = idna_encode(name)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 173, in idna_encode
    return idna.encode(name)
  File "/usr/local/lib/python3.5/dist-packages/idna/core.py", line 350, in encode
    raise IDNAError('Empty domain')
idna.core.IDNAError: Empty domain
172.16.254.216 "POST /v2/apps/ HTTP/1.1" 500 25 "Deis Client v2.13.0"
```
I've tried manually setting `controller.platform_domain` and redeploying deis, but it doesn't affect the outcome.

Thanks for the help!

**Comment by bacongobbler** [comment]
> raise IDNAError('Empty domain')

that's certainly an interesting error. It appears to me that it may be related to your kube config setup within the container itself. In other words, the controller is unable to communicate with the kubernetes master API. Can you check `kubectl --namespace deis exec <my-controller-pod> env` and post the output here, obfuscating the values of the environment variables? I wonder if [KUBERNETES_SERVICE_*](https://github.com/deis/controller/blob/master/rootfs/api/settings/production.py#L249-L254) is missing from the environment causing the URL to be malformed..

**Comment by kwtalley** [comment]
@bacongobbler here is the output with passwords/keys removed:

```
$ kubectl --namespace deis exec deis-controller-1093256487-r3blw env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=deis-controller-1093256487-r3blw
REGISTRATION_MODE=admin_only
EXPERIMENTAL_NATIVE_INGRESS=false
EXPERIMENTAL_NATIVE_INGRESS_HOSTNAME=example.com
APP_STORAGE=minio
DEIS_SECRET_KEY=<REDACTED>
DEIS_REGISTRY_SERVICE_HOST=127.0.0.1
DEIS_REGISTRY_SERVICE_PORT=5555
SLUGRUNNER_IMAGE_NAME=quay.io/deis/slugrunner:v2.3.0
TZ=UTC
DEIS_BUILDER_KEY=<REDACTED>
DEIS_DATABASE_USER=<REDACTED>
K8S_API_VERIFY_TLS=true
DEIS_REGISTRY_LOCATION=on-cluster
DEIS_REGISTRY_SECRET_PREFIX=private-registry
IMAGE_PULL_POLICY=IfNotPresent
DEIS_DATABASE_PASSWORD=<REDACTED>
RESERVED_NAMES=deis, deis-builder, deis-workflow-manager, grafana
WORKFLOW_NAMESPACE=deis
DEIS_ROUTER_PORT_9090_TCP=tcp://172.17.1.198:9090
DEIS_NSQD_SERVICE_PORT=4151
DEIS_NSQD_PORT_4151_TCP_ADDR=172.17.116.50
DEIS_ROUTER_PORT_443_TCP=tcp://172.17.1.198:443
KUBERNETES_PORT_443_TCP_PROTO=tcp
DEIS_MONITOR_INFLUXUI_SERVICE_HOST=172.17.200.166
DEIS_NSQD_SERVICE_PORT_TRANSPORT=4150
DEIS_CONTROLLER_SERVICE_PORT_HTTP=80
DEIS_CONTROLLER_PORT_80_TCP=tcp://172.17.141.11:80
DEIS_REGISTRY_PORT_80_TCP_PROTO=tcp
DEIS_MINIO_SERVICE_HOST=172.17.195.249
DEIS_BUILDER_PORT_2222_TCP=tcp://172.17.191.220:2222
KUBERNETES_SERVICE_PORT_HTTPS=443
DEIS_ROUTER_PORT_2222_TCP_PORT=2222
DEIS_MONITOR_GRAFANA_PORT_80_TCP_PROTO=tcp
DEIS_ROUTER_SERVICE_PORT_HEALTHZ=9090
DEIS_REGISTRY_SERVICE_PORT_HTTP=80
DEIS_ROUTER_PORT_80_TCP_ADDR=172.17.1.198
DEIS_ROUTER_PORT_9090_TCP_PORT=9090
DEIS_LOGGER_REDIS_SERVICE_HOST=172.17.175.66
DEIS_BUILDER_SERVICE_HOST=172.17.191.220
DEIS_WORKFLOW_MANAGER_PORT_80_TCP_ADDR=172.17.124.75
DEIS_NSQD_PORT_4150_TCP_PORT=4150
DEIS_CONTROLLER_SERVICE_PORT=80
DEIS_LOGGER_SERVICE_HOST=172.17.166.48
DEIS_ROUTER_PORT_80_TCP_PORT=80
DEIS_MONITOR_GRAFANA_PORT_80_TCP=tcp://172.17.148.181:80
DEIS_DATABASE_PORT_5432_TCP=tcp://172.17.147.131:5432
DEIS_MONITOR_INFLUXAPI_SERVICE_PORT_TRANSPORT=80
DEIS_MONITOR_INFLUXUI_PORT_80_TCP=tcp://172.17.200.166:80
DEIS_MONITOR_INFLUXUI_PORT_80_TCP_PROTO=tcp
DEIS_BUILDER_PORT=tcp://172.17.191.220:2222
DEIS_LOGGER_REDIS_PORT_6379_TCP=tcp://172.17.175.66:6379
DEIS_ROUTER_PORT_443_TCP_PORT=443
DEIS_ROUTER_PORT=tcp://172.17.1.198:80
DEIS_REGISTRY_PORT_80_TCP=tcp://172.17.8.77:80
DEIS_LOGGER_PORT_80_TCP_PORT=80
DEIS_MINIO_PORT_9000_TCP=tcp://172.17.195.249:9000
DEIS_BUILDER_SERVICE_PORT_SSH=2222
DEIS_ROUTER_PORT_2222_TCP_ADDR=172.17.1.198
DEIS_MONITOR_GRAFANA_SERVICE_HOST=172.17.148.181
DEIS_DATABASE_SERVICE_HOST=172.17.147.131
DEIS_ROUTER_PORT_9090_TCP_PROTO=tcp
DEIS_WORKFLOW_MANAGER_SERVICE_HOST=172.17.124.75
DEIS_WORKFLOW_MANAGER_PORT_80_TCP_PROTO=tcp
DEIS_MINIO_PORT_9000_TCP_PROTO=tcp
DEIS_MONITOR_INFLUXAPI_PORT=tcp://172.17.135.80:80
DEIS_WORKFLOW_MANAGER_PORT_80_TCP=tcp://172.17.124.75:80
DEIS_WORKFLOW_MANAGER_PORT_80_TCP_PORT=80
DEIS_DATABASE_PORT_5432_TCP_ADDR=172.17.147.131
DEIS_DATABASE_SERVICE_PORT=5432
DEIS_LOGGER_SERVICE_PORT_HTTP=80
DEIS_LOGGER_PORT=tcp://172.17.166.48:80
DEIS_MINIO_PORT=tcp://172.17.195.249:9000
DEIS_ROUTER_PORT_2222_TCP=tcp://172.17.1.198:2222
KUBERNETES_PORT_443_TCP=tcp://172.17.0.1:443
KUBERNETES_SERVICE_PORT=443
DEIS_DATABASE_SERVICE_PORT_POSTGRES=5432
DEIS_NSQD_PORT_4151_TCP_PORT=4151
DEIS_ROUTER_SERVICE_PORT_BUILDER=2222
KUBERNETES_SERVICE_HOST=172.17.0.1
DEIS_MONITOR_INFLUXUI_PORT_80_TCP_ADDR=172.17.200.166
DEIS_DATABASE_PORT=tcp://172.17.147.131:5432
DEIS_MONITOR_GRAFANA_PORT=tcp://172.17.148.181:80
DEIS_MONITOR_INFLUXAPI_PORT_80_TCP_PORT=80
DEIS_LOGGER_PORT_80_TCP_PROTO=tcp
DEIS_MINIO_PORT_9000_TCP_PORT=9000
DEIS_ROUTER_PORT_80_TCP_PROTO=tcp
DEIS_DATABASE_PORT_5432_TCP_PROTO=tcp
DEIS_DATABASE_PORT_5432_TCP_PORT=5432
DEIS_CONTROLLER_PORT_80_TCP_ADDR=172.17.141.11
DEIS_LOGGER_PORT_80_TCP=tcp://172.17.166.48:80
DEIS_BUILDER_PORT_2222_TCP_ADDR=172.17.191.220
DEIS_ROUTER_SERVICE_HOST=172.17.1.198
DEIS_LOGGER_REDIS_SERVICE_PORT=6379
DEIS_ROUTER_SERVICE_PORT_HTTP=80
DEIS_CONTROLLER_PORT_80_TCP_PORT=80
DEIS_BUILDER_PORT_2222_TCP_PROTO=tcp
DEIS_ROUTER_SERVICE_PORT=80
DEIS_ROUTER_PORT_9090_TCP_ADDR=172.17.1.198
DEIS_MONITOR_INFLUXUI_SERVICE_PORT=80
DEIS_NSQD_SERVICE_HOST=172.17.116.50
DEIS_CONTROLLER_SERVICE_HOST=172.17.141.11
DEIS_CONTROLLER_PORT_80_TCP_PROTO=tcp
DEIS_WORKFLOW_MANAGER_PORT=tcp://172.17.124.75:80
DEIS_LOGGER_PORT_80_TCP_ADDR=172.17.166.48
DEIS_MINIO_PORT_9000_TCP_ADDR=172.17.195.249
KUBERNETES_PORT=tcp://172.17.0.1:443
DEIS_BUILDER_PORT_2222_TCP_PORT=2222
DEIS_NSQD_PORT_4151_TCP=tcp://172.17.116.50:4151
DEIS_ROUTER_PORT_443_TCP_PROTO=tcp
DEIS_MONITOR_GRAFANA_SERVICE_PORT=80
DEIS_MONITOR_GRAFANA_SERVICE_PORT_UI=80
DEIS_NSQD_SERVICE_PORT_HTTP=4151
DEIS_REGISTRY_PORT=tcp://172.17.8.77:80
DEIS_NSQD_PORT=tcp://172.17.116.50:4151
DEIS_CONTROLLER_PORT=tcp://172.17.141.11:80
DEIS_REGISTRY_PORT_80_TCP_PORT=80
DEIS_MINIO_SERVICE_PORT=9000
DEIS_MONITOR_INFLUXAPI_PORT_80_TCP_ADDR=172.17.135.80
DEIS_MONITOR_INFLUXUI_PORT_80_TCP_PORT=80
DEIS_NSQD_PORT_4150_TCP_ADDR=172.17.116.50
DEIS_WORKFLOW_MANAGER_SERVICE_PORT_HTTP=80
DEIS_ROUTER_PORT_443_TCP_ADDR=172.17.1.198
KUBERNETES_PORT_443_TCP_PORT=443
DEIS_LOGGER_SERVICE_PORT=80
DEIS_MONITOR_GRAFANA_PORT_80_TCP_PORT=80
DEIS_MONITOR_INFLUXUI_SERVICE_PORT_ADMIN=80
DEIS_WORKFLOW_MANAGER_SERVICE_PORT=80
DEIS_BUILDER_SERVICE_PORT=2222
DEIS_MONITOR_GRAFANA_PORT_80_TCP_ADDR=172.17.148.181
KUBERNETES_PORT_443_TCP_ADDR=172.17.0.1
DEIS_MONITOR_INFLUXUI_PORT=tcp://172.17.200.166:80
DEIS_NSQD_PORT_4150_TCP_PROTO=tcp
DEIS_REGISTRY_PORT_80_TCP_ADDR=172.17.8.77
DEIS_MONITOR_INFLUXAPI_SERVICE_HOST=172.17.135.80
DEIS_MONITOR_INFLUXAPI_SERVICE_PORT=80
DEIS_NSQD_PORT_4151_TCP_PROTO=tcp
DEIS_ROUTER_SERVICE_PORT_HTTPS=443
DEIS_ROUTER_PORT_2222_TCP_PROTO=tcp
DEIS_LOGGER_REDIS_PORT_6379_TCP_ADDR=172.17.175.66
DEIS_LOGGER_REDIS_PORT_6379_TCP_PORT=6379
DEIS_MONITOR_INFLUXAPI_PORT_80_TCP_PROTO=tcp
DEIS_NSQD_PORT_4150_TCP=tcp://172.17.116.50:4150
DEIS_ROUTER_PORT_80_TCP=tcp://172.17.1.198:80
DEIS_LOGGER_REDIS_PORT_6379_TCP_PROTO=tcp
DEIS_MONITOR_INFLUXAPI_PORT_80_TCP=tcp://172.17.135.80:80
DEIS_MINIO_SERVICE_PORT_S3=9000
DEIS_LOGGER_REDIS_PORT=tcp://172.17.175.66:6379
TERM=xterm
HOME=/root
```

**Comment by bacongobbler** [comment]
Something tells me your master api server is not available internal to the cluster via 172.17.0.1. Can you confirm this within the pod? If so there's probably some config set up incorrectly with your k8s cluster. I do not know what causes KUBERNETES_SERVICE_HOST to be set inside containers, though I think that's what is causing the root issue here.

**Comment by kwtalley** [comment]
So it appears I can reach the endpoint, but curling 443 shows the cert is not trusted (self-signed at k8s deployment using kismatic. Does that sound like it could be the culprit?

**Comment by bacongobbler** [comment]
At this point I'm not sure what is the root cause but all signs are pointing at the connection between the controller and the kubernetes master API causing the issue, so I would have to assume yes.

**Comment by bacongobbler** [comment]
Did you try adding the mounted certificate in the container to your curl request though?

https://kubernetes.io/docs/concepts/cluster-administration/access-cluster/#accessing-the-api-from-a-pod

**Comment by kwtalley** [comment]
Alright, I curled with the ca-cert loaded via secret and get:
`curl: (51) SSL: certificate subject name (agatha) does not match target host name '172.17.0.1'`, agatha being the node running the apiserver. 

This is starting to feel like a similar issue I uncovered when trying to enable calico policies where it's missing support for mixed IP SAN/DNS SAN in certificates. from my understanding, it only checks against DNS SAN if they exist and forgets the IP SAN. Where my apiservers autogenerated cert SAN is: 
`
DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:agatha, DNS:, IP Address:127.0.0.1, IP Address:172.17.0.1, IP Address:10.2.0.3, IP Address:10.2.0.3, IP Address:10.2.0.3
` 

similar to this issue as an example:
[Policy controller doesn't support mixed IP SANs/DNS SANs](https://github.com/projectcalico/k8s-policy/issues/69)

**Comment by kwtalley** [comment]
Alright, so actually found that since we're using python 3.5, IP/DNS SAN issue was fixed. And after testing reviewing the SANs in my cert, the last DNS one is "" which will definitely throw the empty domain from idna. This can be closed and thank you @bacongobbler for the assistance!

**Comment by bacongobbler** [comment]
Ah yeah I missed that little detail in your cert SAN output above. Good find!

**Comment by xiaoping378** [comment]
deis v2.14.0 on kubeadm v1.6.2 clusters, similar issues....
```
12.240.0.1 "POST /v2/apps/ HTTP/1.1" 500 25 "Deis Client v2.14.0"
12.240.0.1 "POST /v2/apps/ HTTP/1.1" 400 51 "Deis Client v2.14.0"
INFO [steely-lakeside]: config steely-lakeside-f94c987 updated
INFO [steely-lakeside]: admin created initial release
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 20, in perform_create
    obj = serializer.save(owner=self.request.user)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 906, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 393, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/api/models/app.py", line 103, in save
    self.create(*args, **kwargs)
  File "/app/api/models/app.py", line 231, in create
    self._scheduler.ingress.get(ingress)
  File "/app/scheduler/resources/ingress.py", line 21, in get
    raise KubeHTTPException(response, message)
  File "/app/scheduler/exceptions.py", line 10, in __init__
    data = response.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
12.240.0.1 "POST /v2/apps/ HTTP/1.1" 500 25 "Deis Client v2.14.0"

```
