### ISSUE TITLE
500 error creating application

### ISSUE THREAD

**Issue by abh** [deis/workflow#814]
Running on Kubernetes 1.6.2 (using Tectonic, so RBAC etc).

All the pods except the telegraf ones are running and healthy. I created the user okay, but creating an application gives a 500 error.

```
10.2.3.0 "GET / HTTP/1.1" 404 74 "curl/7.51.0"
10.2.5.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.14.0"
10.2.4.0 "POST /v2/auth/register/ HTTP/1.1" 201 240 "Deis Client v2.14.0"
10.2.5.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.14.0"
10.2.3.0 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.14.0"
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 20, in perform_create
    obj = serializer.save(owner=self.request.user)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 906, in create
    instance = ModelClass.objects.create(**validated_data)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 393, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/api/models/app.py", line 92, in save
    if self._scheduler.ns.get(self.id).status_code == 200:
  File "/app/scheduler/resources/namespace.py", line 25, in get
    raise KubeHTTPException(response, message, *args)
  File "/app/scheduler/exceptions.py", line 10, in __init__
    data = response.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
10.2.5.1 "POST /v2/apps/ HTTP/1.1" 500 25 "Deis Client v2.14.0"

**Comment by vdice** [comment]
@abh I believe more permissions were added on top of those listed in the gist.  The latest scheduled to go in are up in PR form in their respective repos.  When/if you have a moment, could you try the same exercise following the instructions listed [here](https://github.com/deis/workflow/pull/812#issuecomment-301204826)?  That should get you a Workflow install w/ all of the updated RBAC permissions.

Do let us know; we're also performing final testing w/ intentions of merging shortly...  Thanks!

**Comment by holyketzer** [comment]
```
$ deis version
v2.16.0
```

I did as described in docs

```
kubectl create sa tiller-deploy -n kube-system
kubectl create clusterrolebinding helm --clusterrole=cluster-admin --serviceaccount=kube-system:tiller-deploy
helm init --service-account=tiller-deploy
```

But I have the same issue

**Comment by semoac** [comment]
In my case, installing deis with --set use_rbac=true solved the problem

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/workflow#19
