### ISSUE TITLE
`deis run` returns 503 code 

### ISSUE THREAD

**Issue by notmaxx** [deis/workflow#853]
```
notmaxx$ deis run -a preview -- ls -l
Running 'ls -l'...
Error: Unknown Error (503): {"detail":"preview-run-2k0a4 (run): Expecting value: line 1 column 1 (char 0)"}
notmaxx$ deis run -a preview -- 'ls -la'
Running 'ls -la'...
Error: Unknown Error (503): {"detail":"preview-run-tyofa (run): Expecting value: line 1 column 1 (char 0)"}
notmaxx$ deis run -a preview -- 'ls -l'
Running 'ls -l'...
Error: Unknown Error (503): {"detail":"preview-run-3jdyg (run): Expecting value: line 1 column 1 (char 0)"}
notmaxx$ deis run -a preview -- "ls -l"
Running 'ls -l'...
Error: Unknown Error (503): {"detail":"preview-run-qps00 (run): Expecting value: line 1 column 1 (char 0)"}
notmaxx$ deis run -a preview -- "ls -la"
Running 'ls -la'...
Error: Unknown Error (503): {"detail":"preview-run-mu40m (run): Expecting value: line 1 column 1 (char 0)"}
```

Client OS: Mac OS
client deis version: `v2.17.0`

k8s cluster runs on AWS set up with `kops`
Controller logs
```
INFO [preview]: admin on preview-run-2k0a4 runs 'ls -l'
INFO:api.models.app:[preview]: admin on preview-run-2k0a4 runs 'ls -l'
INFO [preview]: run preview-run-2k0a4, img quay.io/deis/slugrunner:v2.3.0, entrypoint ['/runner/init'], cmd "['ls -l']"
INFO:scheduler:[preview]: run preview-run-2k0a4, img quay.io/deis/slugrunner:v2.3.0, entrypoint ['/runner/init'], cmd "['ls -l']"
ERROR:root:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/api/models/app.py", line 749, in run
    **data
  File "/app/scheduler/__init__.py", line 311, in run
    self.pod.create(namespace, name, image, **kwargs)
  File "/app/scheduler/resources/pod.py", line 42, in create
    raise KubeHTTPException(response, 'create Pod in Namespace "{}"', namespace)
  File "/app/scheduler/exceptions.py", line 10, in __init__
    data = response.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 241, in run
    rc, output = app.run(self.request.user, request.data['command'])
  File "/app/api/models/app.py", line 755, in run
    raise ServiceUnavailable(err) from e
api.exceptions.ServiceUnavailable: preview-run-2k0a4 (run): Expecting value: line 1 column 1 (char 0)
100.124.0.38 "POST /v2/apps/preview/run HTTP/1.1" 503 79 "Deis Client v2.17.0"
```

```
notmaxx$ helm list
NAME       	REVISION	UPDATED                 	STATUS  	CHART           	NAMESPACE
riotous-cow	2       	Tue Aug 15 18:27:46 2017	DEPLOYED	workflow-v2.16.0	deis 
```

**Comment by Cryptophobia** [comment]
This seems to be breaking for us as well after upgrading to kubernetes 1.7.4 . Any idea on how to fix this. Did the scheduler api endpoint and client change?

**Comment by bacongobbler** [comment]
> Any idea on how to fix this. Did the scheduler api endpoint and client change?

The scheduler client hasn’t changed in significant behavior in months.

Looks like it's failing when attempting to create the pod according to the stack trace [here](https://github.com/deis/controller/blob/master/rootfs/scheduler/resources/pod.py#L37-L42).

**Comment by Cryptophobia** [comment]
Don't know if this is the case for everyone but for us (we enabled rbac in 1.7.4) and it turns out the controller was getting 403 from api calls to the kubernetes api. The fix was to add a clusterrolebinding to deis-controller sa deis:deis-controller which should already exists:

```
kubectl create clusterrolebinding deis-controller --clusterrole=cluster-admin --serviceaccount=deis:deis-controller
```

If serviceaccount deis:deis-controller does not exist, you need to add it with:

```
deis create sa deis-controller -n deis
```

**Comment by bacongobbler** [comment]
In that case, it seems like you need to install workflow with `--set global.use_rbac=true` which will [install the service account for you](https://github.com/deis/controller/blob/master/charts/controller/templates/controller-service-account.yaml). k8s 1.7 enables RBAC by default.

Closing as resolved.

**Comment by Cryptophobia** [comment]
The service account was there but it was not tied to any clusterroles for permissions.

**Comment by bacongobbler** [comment]
The cluster role binding should be [created for you as well](https://github.com/deis/controller/blob/master/charts/controller/templates/controller-clusterrolebinding.yaml) with `use_rbac` enabled.
