### ISSUE TITLE
server error talking to controller when launching during a `git push` based deploy

### ISSUE THREAD

**Issue by arschles** [deis/workflow#99]
On a `git push` from the [`example-go` repo](https://github.com/deis/example-go) (a buildpack build), the following output results:

```console
ENG000656:example-go aaronschlesinger$ git push deis master
The authenticity of host '[deis.micro-kube.local]:2222 ([172.17.8.100]:2222)' can't be established.
ECDSA key fingerprint is SHA256:0ZiwB2heubH7jTpArCHN6Mf009u6TtgDDS99ZwUg/KM.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[deis.micro-kube.local]:2222,[172.17.8.100]:2222' (ECDSA) to the list of known hosts.
Counting objects: 75, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (40/40), done.
Writing objects: 100% (75/75), 18.20 KiB | 0 bytes/s, done.
Total 75 (delta 30), reused 75 (delta 30)
Added host ‘http://10.3.0.36:9000’ successfully.
mc: <ERROR> Unable to make bucket ‘http://10.3.0.36:9000/git’. The requested bucket name is not available.
‘wicker-radiator.tar.gz’ -> ‘http://10.3.0.36:9000/git/home/wicker-radiator:git-5450cbcd/tar’
Total: 2.76 KB, Transferred: 2.76 KB, Speed: 820.28 KB/s
-----> stored tarfile in http://10.3.0.36:9000/git/home/wicker-radiator:git-5450cbcd/tar
-----> creating builder pod in namespace deis
pod "wicker-radiator-git-5450cbcd" created
Waiting for build to complete...
............................................................
Build complete.
-----> Launching... 
2015/12/16 19:29:58 failed retrieving config from controller: <h1>Server Error (500)</h1>
To ssh://git@deis.micro-kube.local:2222/wicker-radiator.git
 * [new branch]      master -> master
```

Note the following:

1. I was able to successfully push and launch a new app yesterday evening
2. This push was done on a fresh deis cluster, fresh app
3. The first two pushes failed, and I saw a traceback in workflow logs (see below), but _subsequent pushes seem to succeed_.

```console
10.2.76.1 "POST /v2/hooks/build HTTP/1.1" 500 27 "deis-builder"
10.2.76.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.0.0-dev"
10.2.76.1 "POST /v2/auth/register/ HTTP/1.1" 400 43 "Deis Client v2.0.0-dev"
10.2.76.1 "GET /v2/ HTTP/1.1" 401 58 "Deis Client v2.0.0-dev"
10.2.76.1 "POST /v2/auth/login/ HTTP/1.1" 200 52 "Deis Client v2.0.0-dev"
10.2.76.1 "POST /v2/keys/ HTTP/1.1" 201 983 "Deis Client v2.0.0-dev"
10.2.76.1 "POST /v2/keys/ HTTP/1.1" 400 41 "Deis Client v2.0.0-dev"
INFO wicker-radiator: config wicker-radiator-fe4aa59 updated
INFO wicker-radiator: release wicker-radiator-v1 created
INFO [wicker-radiator]: arschles created initial release
10.2.76.1 "POST /v2/apps/ HTTP/1.1" 201 208 "Deis Client v2.0.0-dev"
10.2.76.1 "POST /v2/hooks/push HTTP/1.1" 201 448 "curl/7.39.0"
10.2.76.1 "POST /v2/hooks/config HTTP/1.1" 200 203 "deis-builder"
INFO wicker-radiator: build wicker-radiator-630cd8a created
INFO wicker-radiator: release wicker-radiator-v2 created
INFO [wicker-radiator]: arschles deployed 5450cbc
INFO Pulling Docker image 10.3.0.185:5000/wicker-radiator:git-5450cbcd
INFO wicker-radiator: 500 Server Error: Internal Server Error ("invalid registry endpoint https://10.3.0.185:5000/v0/: unable to ping registry endpoint https://10.3.0.185:5000/v0/
v2 ping attempt failed with error: Get https://10.3.0.185:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.3.0.185:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.3.0.185:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.3.0.185:5000/ca.crt")
INFO [wicker-radiator]: 500 Server Error: Internal Server Error ("invalid registry endpoint https://10.3.0.185:5000/v0/: unable to ping registry endpoint https://10.3.0.185:5000/v0/
v2 ping attempt failed with error: Get https://10.3.0.185:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.3.0.185:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.3.0.185:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.3.0.185:5000/ca.crt")
INFO wicker-radiator: arschles scaled containers web=1
INFO [wicker-radiator]: arschles scaled containers web=1
DEBUG scale wicker-radiator_v2.web, img wicker-radiator:v2, params {u'num': 1, u'tags': {}, u'aname': u'wicker-radiator', u'version': u'v2', u'memory': {}, u'cpu': {}}, cmd "start web"
DEBUG create wicker-radiator_v2.web, img wicker-radiator:v2, params {u'version': u'v2', u'tags': {}, u'aname': u'wicker-radiator', u'num': 1, u'memory': {}, u'cpu': {}}, cmd "start web"
ERROR wicker-radiator: wicker-radiator_v2.web (scale): u'containerID'
ERROR [wicker-radiator]: wicker-radiator_v2.web (scale): u'containerID'
ERROR Internal Server Error: /v2/hooks/build
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 403, in create
    super(BuildHookViewSet, self).create(request, *args, **kwargs)
  File "/app/api/views.py", line 129, in create
    return super(BaseDeisViewSet, self).create(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 410, in post_save
    build.create(self.user)
  File "/app/api/models.py", line 738, in create
    self.app.deploy(user, new_release)
  File "/app/api/models.py", line 466, in deploy
    self._default_scale(user, release)
  File "/app/api/models.py", line 510, in _default_scale
    self.scale(user, structure)
  File "/app/api/models.py", line 296, in scale
    self._scale_containers(scale_types, to_remove)
  File "/app/api/models.py", line 329, in _scale_containers
    **kwargs
  File "/app/scheduler/k8s.py", line 295, in scale
    self.create(name, image, command, **kwargs)
  File "/app/scheduler/k8s.py", line 406, in create
    self._create_service(name, app_name, app_type, data)
  File "/app/scheduler/k8s.py", line 436, in _create_service
    container_id = actual_pod['status']['containerStatuses'][0]['containerID'].split("//")[1]
KeyError: u'containerID'
10.2.76.1 "POST /v2/hooks/build HTTP/1.1" 500 27 "deis-builder"
10.2.76.1 "POST /v2/hooks/push HTTP/1.1" 201 448 "curl/7.39.0"
10.2.76.1 "POST /v2/hooks/config HTTP/1.1" 200 203 "deis-builder"
INFO wicker-radiator: build wicker-radiator-52947c0 created
INFO wicker-radiator: release wicker-radiator-v3 created
INFO [wicker-radiator]: arschles deployed 6b2d12b
INFO Pulling Docker image 10.3.0.185:5000/wicker-radiator:git-6b2d12b8
INFO wicker-radiator: 500 Server Error: Internal Server Error ("invalid registry endpoint https://10.3.0.185:5000/v0/: unable to ping registry endpoint https://10.3.0.185:5000/v0/
v2 ping attempt failed with error: Get https://10.3.0.185:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.3.0.185:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.3.0.185:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.3.0.185:5000/ca.crt")
INFO [wicker-radiator]: 500 Server Error: Internal Server Error ("invalid registry endpoint https://10.3.0.185:5000/v0/: unable to ping registry endpoint https://10.3.0.185:5000/v0/
v2 ping attempt failed with error: Get https://10.3.0.185:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.3.0.185:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.3.0.185:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.3.0.185:5000/ca.crt")
DEBUG deploy wicker-radiator_v3.web, img wicker-radiator:v3, params {u'version': u'v3', u'tags': {}, u'aname': u'wicker-radiator', u'num': 0, u'memory': {}, u'cpu': {}}, cmd "start web"
INFO wicker-radiator: arschles scaled containers web=1
INFO [wicker-radiator]: arschles scaled containers web=1
10.2.76.1 "POST /v2/hooks/build HTTP/1.1" 200 65 "deis-builder"
```

**Comment by arschles** [comment]
is this possibly a registry issue?

```console
INFO [wicker-radiator]: 500 Server Error: Internal Server Error ("invalid registry endpoint https://10.3.0.185:5000/v0/: unable to ping registry endpoint https://10.3.0.185:5000/v0/
v2 ping attempt failed with error: Get https://10.3.0.185:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://10.3.0.185:5000/v1/_ping: tls: oversized record received with length 20527. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.3.0.185:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.3.0.185:5000/ca.crt")
```

**Comment by bacongobbler** [comment]
yes, it looks like the docker daemon cannot pull from your registry. Can you output `kubectl get svc deis-registry --namespace=deis`, as well as `sudo cat /etc/sysconfig/docker` for us? Your daemon should have something like `--insecure-registry 10.0.0.0/8` on there by default so docker can communicate with a registry in a pod.

**Comment by bacongobbler** [comment]
e.g. https://github.com/kubernetes/kubernetes/blob/master/cluster/vagrant/config-default.sh#L77

**Comment by arschles** [comment]
@bacongobbler see below.

```console
ENG000656:workflow aaronschlesinger$ kubectl get svc deis-registry --namespace=deis
NAME            CLUSTER_IP   EXTERNAL_IP   PORT(S)    SELECTOR             AGE
deis-registry   10.3.0.163   <none>        5000/TCP   name=deis-registry   32m
core@micro-kube ~/example-go $ sudo cat /etc/sysconfig/docker
cat: /etc/sysconfig/docker: No such file or directory
```

For my next trick, I've tried restarting docker after running `export EXTRA_DOCKER_OPTS="--insecure-registry 10.0.0.0/8"` on the minion. Will update here with result when done.

**Comment by arschles** [comment]
@bacongobbler same issue. should I try running https://github.com/kubernetes/kubernetes/blob/master/cluster/vagrant/config-default.sh on the minion?

**Comment by bacongobbler** [comment]
Setting an envvar for your user session won't add it to EXTRA_DOCKER_OPTS. Since it looks like you're on micro-kube, you'll likely have to follow https://coreos.com/os/docs/latest/registry-authentication.html and add it to the user-data that micro-kube adds to the Vagrantfile. From looking at the code it doesn't seem to set up the box with `--insecure-registry 10.0.0.0`.

> should I try running https://github.com/kubernetes/kubernetes/blob/master/cluster/vagrant/config-default.sh on the minion?

That won't work with micro-kube. I'd recommend following the [official documentation](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/vagrant.md) on getting set up with Vagrant.

**Comment by bacongobbler** [comment]
demoting as a bug/showstopper. This is a third party issue (micro-kube).

**Comment by arschles** [comment]
thanks @bacongobbler

**Comment by slack** [comment]
Running into this one as well. My k8s came from coreos-kubernetes, running on AWS.

**Comment by slack** [comment]
Need to doc the requirements that the k8s cluster be provisioned with insecure registry. in deis/workflow#6 or otherwise

**Comment by technosophos** [comment]
@slack wanna file an issue for that and mark it showstopper?

**Comment by bacongobbler** [comment]
Good point. If it's more than just one non-official project I'll document it.

**Comment by technosophos** [comment]
Yeah, we're not going to be able to document this for every non-official. Probably just pointing out how it is to be done using the official k8s.io versions is enough.

**Comment by bacongobbler** [comment]
Actually, this is already documented: https://github.com/deis/workflow/blob/master/docs/src/installing-deis/system-requirements.md#network

**Comment by krancour** [comment]
> Running into this one as well. My k8s came from coreos-kubernetes, running on AWS.

Same here.

**Comment by krancour** [comment]
> From looking at the code it doesn't seem to set up the box with --insecure-registry 10.0.0.0.

fwiw, that _is_ accounted for in the `active-dev` branch:

https://github.com/krancour/micro-kube/blob/active-dev/user-data#L54

**Comment by arschles** [comment]
@krancour awesome. thanks for letting me know

**Comment by arschles** [comment]
I think since we have docs in place and this is not a bug with deis, we can close. thoughts?

**Comment by krancour** [comment]
I'm interested in knowing how we plan to address this long term.  Do we intend on running _secure_ registries eventually?  If not, this will be a very limiting factor in terms of what k8s clusters we can actually run on.

I opened an issue against coreos-kubernetes, for instance, because @slack and I both ran into this there.  I figured out on my own how to work around this:

https://github.com/coreos/coreos-kubernetes/issues/210

But considering that your average user might not have had the foresight to enable insecure registries at the time they provision their cluster, or they may not _want_ to for security reasons, should we have a more bullet-proof answer to this problem?

**Comment by arschles** [comment]
>Do we intend on running secure registries eventually?

We've talked randomly and informally about coming up with a holistic problem to issuing certificates, and if we had something in place to do so I think we could, and should run secure registries fairly easily. Our minio component, and I think router would also benefit.

>your average user might not have had the foresight to enable insecure registries at the time they provision their cluster

I agree. Maybe we should put another sentence or two under https://github.com/deis/workflow/blob/master/docs/src/installing-deis/system-requirements.md#network

>should we have a more bullet-proof answer to this problem?

IMO yes, but I don't know what it is. Listing instructions on how to enable insecure registries for every provisioning tool doesn't seem like the answer.

**Comment by krancour** [comment]
Reopening... I am still encountering the issue described in the OP, and I'm long past any insecure registry issues.

**Comment by bacongobbler** [comment]
fwiw I'm on a 5-node AWS cluster, and I haven't seen this issue pop up.

**Comment by technosophos** [comment]
Okay, this issue got re-opened, but without any additional information about what the problem is. Please either post logs showing the current error or remove this from the showstopper list.

Are we hunting for a big stack trace or a registry issue?

**Comment by technosophos** [comment]
And again, _SSL issues are not showstoppers for alpha_. Insecure registry is an SSL issue.

**Comment by krancour** [comment]
Sorry for not posting additional logs.  I wasn't seeing anything that wasn't in the OP.  I am no longer encountering this now.
